In [ ]:
#Task1

import numpy as np
X = np.arange(2, 34, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [ ]:
#Task2

import numpy as np

X = np.arange(1, 26).reshape(5, 5)
Y = X[X % 2 != 0]

print(X)
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [ ]:
#Task3

import numpy as np
X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [ ]:

#task4
import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)


# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[ 0.384045   -1.05396878  1.08848234 ...  0.40953335  1.48362917
   0.74051721]
 [ 1.20828598 -0.04421769 -0.88253883 ...  0.85167367 -0.23774087
  -1.32288248]
 [ 1.25069506  0.45690794 -1.50923333 ... -0.72401697  0.37867222
   1.27531953]
 ...
 [ 1.51814587 -1.24351017 -0.18746484 ...  1.38711605 -0.52683652
  -0.53997599]
 [-1.06743995 -0.25830401 -0.98898525 ... -0.33688308 -1.33435852
   0.67159938]
 [-0.16658902  0.55849667 -0.83671752 ... -1.70508109 -0.66860458
   1.55099083]]
Average of all values in X_norm: -2.5579538487363606e-17
Average of minimum values in each column of X_norm: -1.7357449515188272
Average of maximum values in each column of X_norm: 1.7286881119620392
Random permutation of row indices: [236 156 798 855 444  18 694 973 869 506 360 475 843 320 354 144 832 247
 104 259 769 710 491 538 847 721 365 647 521 143 773 516 398 772 224 520
 967 752 613  51 831 587 904 108 564 884 322   